- name: Checkout dotfiles repository
  git:
    repo: https://github.com/garbast/dotfiles.git
    dest: /home/.dotfiles
    umask: "002"
    update: no

- name: Checkout powerlevel10k repository
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ username }}/.oh-my-zsh/themes/powerlevel10k"
    umask: "002"

- name: Change the ownership of oh-my-zsh themes
  become: yes
  file:
    path: "/home/{{ username }}/.oh-my-zsh/themes/powerlevel10k"
    owner: "{{ username }}"
  register: chgrpout

- name: Link profile settings
  file:
    src: /home/.dotfiles/.profile
    dest: "/home/{{ username }}/.profile"
    owner: "{{ username }}"
    state: link
    force: true

- name: Link git settings
  file:
    src: /home/.dotfiles/.gitconfig
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"
    state: link
    force: true

- name: Link zsh settings
  file:
    src: /home/.dotfiles/.zshrc
    dest: "/home/{{ username }}/.zshrc"
    owner: "{{ username }}"
    state: link
    force: true

- name: Link p10k settings
  file:
    src: /home/.dotfiles/.p10k.zsh
    dest: "/home/{{ username }}/.p10k.zsh"
    owner: "{{ username }}"
    state: link
    force: true
