- name: Ensure Nextcloud Client ppa is present
  apt_repository:
    repo: ppa:nextcloud-devs/client

- name: Install Nextcloud Client
  apt:
    name: nextcloud-client
    update_cache: yes
    cache_valid_time: 86400
    state: latest
