- name: Ensure LibreOffice ppa is present
  apt_repository:
    repo: ppa:libreoffice/ppa

- name: Install LibreOffice
  apt:
    name: libreoffice
    update_cache: yes
    cache_valid_time: 86400
    state: latest
