- stat:
    path: /etc/apparmor.d/disable/usr.sbin.mysqld
  register: symlink

- name: Disable app armor for mariadb
  file:
    src: /etc/apparmor.d/usr.sbin.mysqld
    dest: /etc/apparmor.d/disable/usr.sbin.mysqld
    state: link
  when: symlink.stat.islnk is not defined

- name: Create folder for dont protect file
  file:
    path: /etc/systemd/system/mariadb.service.d/
    state: directory

- name: Disable home protection of systemd
  copy:
    src: dontprotecthome.conf
    dest: /etc/systemd/system/mariadb.service.d/dontprotecthome.conf
