- name: Ensure transport tools are installed
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes
    cache_valid_time: 86400
    state: latest
  tags: docker

- name: Add an Apt signing key, used to install docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags: docker

- name: Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    cache_valid_time: 86400
    state: latest
  tags: docker

- name: "Add remote {{ username }} user to docker group"
  user:
    name: "{{ username }}"
    group: "docker"
    append: yes
  tags: docker

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false
  tags: docker

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
    dest: "/usr/local/bin/docker-compose"
    mode: "0755"
  when: docker_compose_current_version.stdout is not defined
  tags: docker
