php:
  php7.2:
    install:
      version: 7.2
      pool_folder: /etc/php/7.2/fpm/pool.d
      packages:
        - php7.2
        - php7.2-fpm
        - php7.2-bcmath
        - php7.2-bz2
        - php7.2-cli
        - php7.2-common
        - php7.2-curl
        - php7.2-dev
        - php7.2-gd
        - php7.2-json
        - php7.2-mbstring
        #- php7.2-mcrypt
        - php7.2-mysql
        - php7.2-sqlite3
        - php7.2-soap
        - php7.2-xml
        - php7.2-zip
        - php7.2-intl
        - php-apcu
        - php-xdebug
    config: |
      [debug]
      xdebug.idekey = PHPSTORM
      xdebug.max_nesting_level = 400
      xdebug.remote_connect_back = 1
      xdebug.remote_enable = 1
