php:
  php5.6:
    install:
      version: 5.6
      pool_folder: /etc/php/5.6/fpm/pool.d
      packages:
        - php5.6
        - php5.6-fpm
        - php5.6-bz2
        - php5.6-cli
        - php5.6-common
        - php5.6-dev
        - php5.6-json
        - php5.6-gd
        - php5.6-mcrypt
        - php5.6-mbstring
        - php5.6-mysql
        - php5.6-sqlite3
        - php5.6-soap
        - php5.6-xml
        - php5.6-zip
        - php-apcu
        - php-xdebug
    config: |
      [debug]
      xdebug.idekey = PHPSTORM
      xdebug.max_nesting_level = 400
      xdebug.remote_connect_back = 1
      xdebug.remote_enable = 1
